version: 2.1

executors:
  default:
    description: The default executor used for the build jobs
    parameters:
      tag:
        description: The cimg/ruby Docker image version tag
        type: string
        default: latest
    docker:
      - image: cimg/ruby:<< parameters.tag >>
      - image: circleci/postgres:latest-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: database_consistency_test
          POSTGRES_PASSWORD: database_consistency_password
      - image: circleci/mysql:latest-ram
        environment:
          MYSQL_ROOT_HOST: "%"
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: database_consistency_password
          MYSQL_DATABASE: database_consistency_test
    environment:
      DB_HOST: 127.0.0.1
      DB_USER: root
      DB_PASSWORD: database_consistency_password
    working_directory: ~/dc

jobs:
  checkout:
    docker:
      - image: cimg/base:stable
    working_directory: ~/dc
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/dc
          paths:
            - .

  build:
    parameters:
      ruby-version:
        type: string
      gemfile:
        type: string
    executor:
      name: default
      tag: << parameters.ruby-version >>
    steps:
      - attach_workspace:
          at: ~/dc
      - run:
          name: Use << parameters.gemfile >> as the Gemfile
          command: bundle config --global gemfile << parameters.gemfile >>
      - run:
          name: Install the gems specified by the Gemfile
          command: bundle install
      - run:
          name: Waiting for PostgreSQL to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 2m

      - run:
          name: Waiting for MySQL to be ready
          command: dockerize -wait tcp://localhost:3306 -timeout 2m
      - run:
          name: Running RSpec
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress
      - store_test_results:
          path: test_results

workflows:
  version: 2
  default: &default
    jobs:
      - checkout
      - build:
          requires:
            - checkout
          matrix:
            parameters:
              ruby-version: [
                "2.4",
                "2.5",
                "2.6",
                "2.7",
                "3.0",
                "latest"
              ]
              gemfile: [
                "gemfiles/ar_4_2.gemfile",
                "gemfiles/ar_5_2.gemfile",
                "gemfiles/ar_6_0.gemfile",
                "gemfiles/ar_6_1.gemfile",
                "gemfiles/ar_7_0.gemfile"
              ]
          name: build-ruby-<< matrix.ruby-version >>/ar-<< matrix.gemfile >>
